Adding a througput chart to the benchmark summary.
bheisler/criterion.rs pull request #315
Opened 2019-08-21 00:18 UTC by gz

A first version to address  #149. This adds a throughput chart to the summary page rather than for an individual test, which is what #149 was originally about and I think it makes more sense (for an individual test it's kind of pointless, I think the one number in the table works fine).

Some more thoughts:

It was a bit of a nuisance to get the Throughput struct down to the reporting and plotting, maybe there is an easier, better way that I don't know?

Also, plot::line_comparison_throughput is doing unwrap on Option<Throughput> so the caller should check that every BenchmarkId has a throughput (and that its of the same type probably). I can add that if the general direction of this pull request is deemed fine.

Maybe, instead of a line-plot a Barchart will work better here?

2019-08-21 19:20 UTC, gz commented
It seems I got confused by the two structs report::BenchmarkId which has throughput and BenchmarkId which doesn't store throughput in benchmark_group.rs which I also mistakenly assumed I was passing around. 
So I can simplify this pull request quite a bit.

2019-08-22 03:41 UTC, bheisler commented
Hey, sorry I haven't had a chance to respond to this yet. Yeah, `report::BenchmarkID` is the way to go. I should also mention there's also a `ValueFormatter::scale_for_throughput` that I added specifically to support this; I haven't looked at the code changes yet so you may have seen that already.

2019-08-25 14:41 UTC, bheisler requested changes
As you noticed, you can get the throughput out of the benchmark ID so all of the changes made to pass the throughput along are unnecessary. There's also some leftover debug output.

Otherwise this looks good. It won't make it into 0.3.0 (which I plan to release today) but it won't require a breaking change so we can add it to 0.3.1.

2019-08-25 14:41 UTC, bheisler commented on src/plot/summary.rs
> +                error!("{:?}", y[0]);
Leftover debugging output.

2019-08-26 23:02 UTC, gz commented on src/html/mod.rs
> +        if value_types.iter().all(|x| x == &value_types[0])
Does this if() cover all cases?

2019-08-26 23:03 UTC, gz commented
Thanks, I updated this pull request, let's see if it passes CI.

2019-08-26 23:47 UTC, bheisler requested changes
Better! Just some minor things to clean up.

2019-08-26 23:47 UTC, bheisler commented on src/html/mod.rs
> +        if value_types.iter().all(|x| x == &value_types[0])
I think this test will return false if there are multiple different throughput values. For example, some benchmarks could have a throughput of `Bytes(1000u64)` and others could be `Bytes(500u64)`, and that would register as different throughput types. I think what you want is to check if they're all either `Bytes(_)` or `Elems(_)`. In that case, I think something like this should work:

```
let all_throughputs_match = value_types.iter().all(|x| x == &value_types[0]) && throughput_types[0].is_some();
if all_throughputs_match { ... }
```

You don't need the third clause because if all of the value-types match then the throughputs must all have the same variant. Maybe add a comment explaining that though, it's not obvious from reading the code.

2019-08-26 23:47 UTC, bheisler commented on src/plot/summary.rs
> +    value_type: ValueType,
Taking the value type as a parameter here is unnecessary; you can get that information from the throughputs in the BenchmarkIDs. Removing it also allows you to simplify the calling code a bit.

2019-08-26 23:47 UTC, bheisler commented on src/plot/summary.rs
> +    let mut i = 0;
Move this down to the loop where it's used.

2019-09-23 23:37 UTC, gz commented
Finally got around to addressing the reviews.

The build currently fails due to unrelated issues,should be fixed with #336

2019-09-24 03:06 UTC, gz commented
I changed the plotting for throughput slightly to take into account parameterized benchmarks. Before it would show them as a single connected line which made it hard to distinguish different parameters. Now they are represented with different labels:

A parameterized benchmark with two configurations options threads and batch size:
![lines_tput](https://user-images.githubusercontent.com/127654/65478080-32503780-de3d-11e9-81fb-c3b4e8785556.png)

A non-parameterized benchmark (from_elem):
![lines_tput_non_parameterized](https://user-images.githubusercontent.com/127654/65478101-3e3bf980-de3d-11e9-8514-273567028dc4.png)

2020-05-15 20:08 UTC, Ekleog commented
Hey! Just wanted to ask if there's any news on this PR, as it'd be very nice :)

2020-05-15 20:24 UTC, gz commented
Hey, the branch/PR works/worked for me -- feel free to give it a try ... Unfortunately, I couldn't quite fit my requirements for a multi-core benchmark harness into criterion (even with `iter_custom`) so I am currently not actively relying on the patch but maybe @bheisler could still check if it's something for master if it's useful for you.

2020-05-27 12:42 UTC, Heep042 commented
It would be really nice to have this in. Although it fails to generate a plot for logarithmic scale (min yrange can't be zero). That should can be solved by removing `set(Range::Limits(0, max_formatted[0])` (line 181 from summary.rs). If this is still of interest to @bheisler I could take over this and finish implementing the feature.

2020-05-31 20:15 UTC, bheisler commented
Hey folks, thanks for your patience. Yeah, if someone else wants to take over and finish this off, that'd be great!

2021-07-26 03:17 UTC, Lemmih commented
> It would be really nice to have this in. Although it fails to generate a plot for logarithmic scale (min yrange can't be zero). That should can be solved by removing `set(Range::Limits(0, max_formatted[0])` (line 181 from summary.rs). If this is still of interest to @bheisler I could take over this and finish implementing the feature.

I'm ready to review if you take over this PR.

2021-12-28 11:59 UTC, Lemmih commented
Closing due to inactivity.

2021-12-28 11:59 UTC, closed without merging